use std::collections::BTreeMap;
use std::fs::File;
use std::io::{self, Cursor, Read};
use std::path::Path;
use std::time::Duration;

use sha2::{Digest as _, Sha512};
use xz2::read::XzDecoder;
use xz2::stream::Stream;

use crate::command::{ScratchDir, hash_file};
use crate::{Result, message};

const MAX_CONTAINER_BYTES: u64 = 512 * 1024 * 1024;
const MAX_REGISTRY_BYTES: u64 = 512 * 1024 * 1024;
const MAX_XZ_DECODER_MEMORY_BYTES: u64 = 128 * 1024 * 1024;
const TARGETS: &[&str] = &["x86_64-linux", "windows", "universal-darwin"];
const XZ_MAGIC: &[u8] = b"\xFD7zXZ\0";
const SNAPSHOT_USER_AGENT: &str =
    "Wget/1.21.4 (compatible; texe-snapshot-generator; +https://github.com/backmatter/texe)";

pub(crate) fn generate(
    snapshot: &str,
    base: &str,
    biber_version: &str,
    component_recipe: &str,
) -> Result<()> {
    let base = base.trim_end_matches('/');
    validate(snapshot, base)?;
    validate_identifier("--biber-version", biber_version)?;
    validate_identifier("--biber-component-recipe", component_recipe)?;

    let scratch = ScratchDir::new("snapshot")?;
    let agent: ureq::Agent = ureq::Agent::config_builder()
        .user_agent(SNAPSHOT_USER_AGENT)
        .timeout_global(Some(Duration::from_secs(900)))
        .build()
        .into();
    eprintln!("snapshot: reading {base}");
    let registry_path = scratch.path().join("texlive.tlpdb");
    let registry_sha256 = download_registry(
        &agent,
        &format!("{base}/tlpkg/texlive.tlpdb.xz"),
        &registry_path,
    )?;

    let mut output = format!(
        "# Generated by `cargo xtask snapshot` from {base}.\n\
         schema = \"texe.toolchain-recipe/v1\"\n\
         snapshot = \"{snapshot}\"\n\
         tlnet_base = \"{base}\"\n\
         sources = [\"{base}\"]\n\
         registry_sha256 = \"{registry_sha256}\"\n\n\
         [biber]\n\
         version = \"{biber_version}\"\n\
         component_recipe = \"{component_recipe}\"\n\n\
         [engines.pdflatex]\n\
         runtime_name = \"pdftex\"\n\
         executable = \"pdftex\"\n\
         format_recipe = \"pdflatex-english-fontmaps-synctex-sourcedate-v1\"\n\
         bootstrap_providers = [\n\
         \u{20}\u{20}\"amsfonts\",\n\
         \u{20}\u{20}\"babel\",\n\
         \u{20}\u{20}\"cm\",\n\
         \u{20}\u{20}\"dehyph\",\n\
         \u{20}\u{20}\"dvips\",\n\
         \u{20}\u{20}\"firstaid\",\n\
         \u{20}\u{20}\"hyph-utf8\",\n\
         \u{20}\u{20}\"hyphen-base\",\n\
         \u{20}\u{20}\"knuth-lib\",\n\
         \u{20}\u{20}\"l3backend\",\n\
         \u{20}\u{20}\"l3kernel\",\n\
         \u{20}\u{20}\"latex\",\n\
         \u{20}\u{20}\"latex-fonts\",\n\
         \u{20}\u{20}\"latexconfig\",\n\
         \u{20}\u{20}\"tex-ini-files\",\n\
         \u{20}\u{20}\"texlive-scripts\",\n\
         \u{20}\u{20}\"unicode-data\",\n\
         ]\n\n\
         [engines.lualatex]\n\
         runtime_name = \"luahbtex\"\n\
         executable = \"luahbtex\"\n\
         format_recipe = \"lualatex-english-texmf-fonts-only-synctex-sourcedate-v1\"\n\
         bootstrap_providers = [\n\
         \u{20}\u{20}\"babel\",\n\
         \u{20}\u{20}\"cm\",\n\
         \u{20}\u{20}\"dvips\",\n\
         \u{20}\u{20}\"firstaid\",\n\
         \u{20}\u{20}\"hyphen-base\",\n\
         \u{20}\u{20}\"knuth-lib\",\n\
         \u{20}\u{20}\"l3backend\",\n\
         \u{20}\u{20}\"l3kernel\",\n\
         \u{20}\u{20}\"latex\",\n\
         \u{20}\u{20}\"latex-fonts\",\n\
         \u{20}\u{20}\"latexconfig\",\n\
         \u{20}\u{20}\"lm\",\n\
         \u{20}\u{20}\"lua-uni-algos\",\n\
         \u{20}\u{20}\"luaotfload\",\n\
         \u{20}\u{20}# LaTeX preloads glyphtounicode.tex for LuaTeX from this generic package.\n\
         \u{20}\u{20}\"pdftex\",\n\
         \u{20}\u{20}\"tex-ini-files\",\n\
         \u{20}\u{20}\"texlive-scripts\",\n\
         \u{20}\u{20}\"unicode-data\",\n\
         ]\n"
    );
    let mut cache = BTreeMap::new();
    for target in TARGETS {
        emit_platform(&agent, base, target, &mut cache, &mut output)?;
    }
    print!("{output}");
    Ok(())
}

fn emit_platform(
    agent: &ureq::Agent,
    base: &str,
    target: &str,
    cache: &mut BTreeMap<String, Vec<u8>>,
    output: &mut String,
) -> Result<()> {
    let executable_suffix = if target == "windows" { ".exe" } else { "" };
    let biber = provider("+biber", target);
    let biber_artifact = artifact(agent, base, &biber, cache)?;
    output.push_str(&format!(
        "\n[platforms.{target}]\nexecutable_suffix = \"{executable_suffix}\"\n"
    ));
    if target == "x86_64-linux" {
        output.push_str(
            "biber_compatibility_library_entry = \
             \"shlib/x86_64-linux-thread-multi/libcrypt.so.1\"\n",
        );
    }
    output.push_str(&format!("biber = {biber_artifact}\n"));
    output.push_str(&format!("\n[platforms.{target}.artifacts]\n"));
    for engine in ["pdflatex", "lualatex"] {
        output.push_str(&format!("{engine} = [\n"));
        for name in providers(engine, target)? {
            output.push_str("  ");
            output.push_str(&artifact(agent, base, &name, cache)?);
            output.push_str(",\n");
        }
        output.push_str("]\n");
    }
    Ok(())
}

fn artifact(
    agent: &ureq::Agent,
    base: &str,
    provider: &str,
    cache: &mut BTreeMap<String, Vec<u8>>,
) -> Result<String> {
    eprintln!("snapshot:   {provider}");
    let bytes = match cache.get(provider) {
        Some(bytes) => bytes,
        None => {
            let bytes = download_xz(agent, &format!("{base}/archive/{provider}.tar.xz"))?;
            cache.entry(provider.to_string()).or_insert(bytes)
        }
    };
    Ok(format!(
        "{{ provider = \"{provider}\", sha512 = \"{}\", size = {} }}",
        hex::encode(Sha512::digest(bytes)),
        separated(bytes.len())
    ))
}

fn download(agent: &ureq::Agent, url: &str) -> Result<Vec<u8>> {
    let response = agent.get(url).call()?;
    let mut bytes = Vec::new();
    response
        .into_body()
        .into_reader()
        .take(MAX_CONTAINER_BYTES + 1)
        .read_to_end(&mut bytes)?;
    if u64::try_from(bytes.len())? > MAX_CONTAINER_BYTES {
        return Err(message(format!("download exceeds 512 MiB: {url}")));
    }
    Ok(bytes)
}

fn download_xz(agent: &ureq::Agent, url: &str) -> Result<Vec<u8>> {
    let bytes = download(agent, url)?;
    if !bytes.starts_with(XZ_MAGIC) {
        return Err(message(format!(
            "snapshot source returned a non-XZ response: {url}"
        )));
    }
    Ok(bytes)
}

fn download_registry(agent: &ureq::Agent, url: &str, output: &Path) -> Result<String> {
    let response = agent.get(url).call()?;
    let compressed = response
        .into_body()
        .into_reader()
        .take(MAX_CONTAINER_BYTES.saturating_add(1));
    unpack_registry(compressed, output)?;
    hash_file(output)
}

fn unpack_registry(mut compressed: impl Read, output: &Path) -> Result<()> {
    let mut magic = [0_u8; XZ_MAGIC.len()];
    compressed.read_exact(&mut magic)?;
    if magic != XZ_MAGIC {
        return Err(message("snapshot source returned a non-XZ registry"));
    }
    let stream = Stream::new_stream_decoder(MAX_XZ_DECODER_MEMORY_BYTES, 0)?;
    let input = Cursor::new(magic).chain(compressed);
    let decoder = XzDecoder::new_stream(input, stream);
    let mut expanded = decoder.take(MAX_REGISTRY_BYTES.saturating_add(1));
    let mut file = File::create(output)?;
    let size = io::copy(&mut expanded, &mut file)?;
    if size > MAX_REGISTRY_BYTES {
        return Err(message("expanded TeX Live registry exceeds 512 MiB"));
    }
    file.sync_all()?;
    Ok(())
}

fn providers(engine: &str, target: &str) -> Result<Vec<String>> {
    let names = match engine {
        "pdflatex" => vec![
            "+bibtex",
            "kpathsea",
            "+kpathsea",
            "makeindex",
            "+makeindex",
            "pdftex",
            "+pdftex",
        ],
        "lualatex" => {
            let mut names = vec![
                "+bibtex",
                "kpathsea",
                "+kpathsea",
                "makeindex",
                "+makeindex",
                "luatex",
            ];
            // On Windows, luahbtex.dll uses the Lua and C runtime DLLs shipped
            // by the platform-specific LuaTeX package.
            if target == "windows" {
                names.push("+luatex");
            }
            names.extend(["luahbtex", "+luahbtex"]);
            names
        }
        _ => return Err(message(format!("unsupported engine {engine}"))),
    };
    Ok(names.iter().map(|name| provider(name, target)).collect())
}

fn provider(package: &str, target: &str) -> String {
    package.strip_prefix('+').map_or_else(
        || package.to_string(),
        |package| format!("{package}.{target}"),
    )
}

fn separated(size: usize) -> String {
    let digits = size.to_string();
    let mut output = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, character) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index).is_multiple_of(3) {
            output.push('_');
        }
        output.push(character);
    }
    output
}

fn validate(snapshot: &str, base: &str) -> Result<()> {
    let date = snapshot
        .strip_prefix("texlive-")
        .ok_or_else(|| message("--snapshot must be texlive-YYYY-MM-DD"))?;
    let valid_date = date.len() == 10
        && date.as_bytes()[4] == b'-'
        && date.as_bytes()[7] == b'-'
        && date
            .bytes()
            .enumerate()
            .all(|(index, byte)| matches!(index, 4 | 7) || byte.is_ascii_digit());
    if !valid_date {
        return Err(message("--snapshot must be texlive-YYYY-MM-DD"));
    }
    let expected = format!("/{}/{}/{}/tlnet", &date[0..4], &date[5..7], &date[8..10]);
    if !base.starts_with("https://") || !base.ends_with(&expected) {
        return Err(message(format!(
            "--base must be the dated HTTPS tree for {snapshot}"
        )));
    }
    Ok(())
}

fn validate_identifier(option: &str, value: &str) -> Result<()> {
    if value.is_empty()
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-' | b'+'))
    {
        return Err(message(format!("{option} has an invalid value")));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::io::{Cursor, Write as _};

    use xz2::write::XzEncoder;

    use super::{providers, unpack_registry};

    #[test]
    fn windows_lualatex_includes_luatex_runtime_dlls() {
        let windows = providers("lualatex", "windows").expect("Windows providers");
        assert!(windows.iter().any(|provider| provider == "luatex.windows"));

        let linux = providers("lualatex", "x86_64-linux").expect("Linux providers");
        assert!(
            linux
                .iter()
                .all(|provider| provider != "luatex.x86_64-linux")
        );
    }

    #[test]
    fn registry_is_streamed_from_xz_to_disk() {
        let contents = b"registry contents";
        let mut encoder = XzEncoder::new(Vec::new(), 6);
        encoder.write_all(contents).expect("encode registry");
        let compressed = encoder.finish().expect("finish XZ stream");
        let scratch = tempfile::tempdir().expect("temporary directory");
        let output = scratch.path().join("texlive.tlpdb");

        unpack_registry(Cursor::new(compressed), &output).expect("unpack registry");
        assert_eq!(fs::read(output).expect("registry contents"), contents);
    }

    #[test]
    fn registry_rejects_non_xz_input() {
        let scratch = tempfile::tempdir().expect("temporary directory");
        let output = scratch.path().join("texlive.tlpdb");
        let error = unpack_registry(Cursor::new(b"not xz"), &output).expect_err("invalid registry");
        assert!(error.to_string().contains("non-XZ"));
    }
}
